extends Node

const Body_preload = {
	0 : preload("res://Character_Customization/Body/Body_1.tres"),
	1 : preload("res://Character_Customization/Body/Body_2.tres"),
	2 : preload("res://Character_Customization/Body/Body_3.tres"),
	3 : preload("res://Character_Customization/Body/Body_4.tres"),
	4 : preload("res://Character_Customization/Body/Body_5.tres"),
	5 : preload("res://Character_Customization/Body/Body_6.tres"),
	6 : preload("res://Character_Customization/Body/Body_7.tres"),
	7 : preload("res://Character_Customization/Body/Body_8.tres"),
	8 : preload("res://Character_Customization/Body/Body_9.tres"),
	9 : preload("res://Character_Customization/Body/Body_10.tres"),
	10: preload("res://Character_Customization/Body/Body_11.tres"),
	11: preload("res://Character_Customization/Body/Body_12.tres"),
	12: preload("res://Character_Customization/Body/Body_13.tres"),
	13: preload("res://Character_Customization/Body/Body_14.tres"),
	14: preload("res://Character_Customization/Body/Body_15.tres"),
	15: preload("res://Character_Customization/Body/Body_16.tres"),
}
const Head_preload = {
	0 : preload("res://Character_Customization/Head/Head_1.tres"),
	1 : preload("res://Character_Customization/Head/Head_2.tres"),
	2 : preload("res://Character_Customization/Head/Head_3.tres"),
	3 : preload("res://Character_Customization/Head/Head_4.tres"),
	4 : preload("res://Character_Customization/Head/Head_5.tres"),
	5 : preload("res://Character_Customization/Head/Head_6.tres"),
	6 : preload("res://Character_Customization/Head/Head_7.tres"),
	7 : preload("res://Character_Customization/Head/Head_8.tres"),
	8 : preload("res://Character_Customization/Head/Head_9.tres"),
	9 : preload("res://Character_Customization/Head/Head_10.tres"),
	10 : preload("res://Character_Customization/Head/Head_11.tres"),
	11 : preload("res://Character_Customization/Head/Head_12.tres"),
	12 : preload("res://Character_Customization/Head/Head_13.tres"),
	13 : preload("res://Character_Customization/Head/Head_14.tres"),
	14 : preload("res://Character_Customization/Head/Head_15.tres"),
	15 : preload("res://Character_Customization/Head/Head_16.tres"),
	16 : preload("res://Character_Customization/Head/Head_17.tres"),
	17 : preload("res://Character_Customization/Head/Head_18.tres"),
	18 : preload("res://Character_Customization/Head/Head_19.tres"),
	19 : preload("res://Character_Customization/Head/Head_20.tres"),
	20 : preload("res://Character_Customization/Head/Head_21.tres"),
	21 : preload("res://Character_Customization/Head/Head_22.tres"),
	22 : preload("res://Character_Customization/Head/Head_23.tres"),
	23 : preload("res://Character_Customization/Head/Head_24.tres"),
	24 : preload("res://Character_Customization/Head/Head_25.tres"),
	25 : preload("res://Character_Customization/Head/Head_26.tres"),
}
const Larm_preload = {
	0 : preload("res://Character_Customization/Larm/Larm_1.tres"),
	1 : preload("res://Character_Customization/Larm/Larm_2.tres"),
	2 : preload("res://Character_Customization/Larm/Larm_3.tres"),
	3 : preload("res://Character_Customization/Larm/Larm_4.tres"),
	4 : preload("res://Character_Customization/Larm/Larm_5.tres"),
	5 : preload("res://Character_Customization/Larm/Larm_6.tres"),
	6 : preload("res://Character_Customization/Larm/Larm_7.tres"),
	7 : preload("res://Character_Customization/Larm/Larm_8.tres"),
	8 : preload("res://Character_Customization/Larm/Larm_9.tres"),
	9 : preload("res://Character_Customization/Larm/Larm_10.tres"),
	10 : preload("res://Character_Customization/Larm/Larm_11.tres"),
	11 : preload("res://Character_Customization/Larm/Larm_12.tres"),
	12 : preload("res://Character_Customization/Larm/Larm_13.tres"),
	13 : preload("res://Character_Customization/Larm/Larm_14.tres"),
	14 : preload("res://Character_Customization/Larm/Larm_15.tres"),
	15 : preload("res://Character_Customization/Larm/Larm_16.tres"),
}
const Rarm_preload = {
	0 : preload("res://Character_Customization/Rarm/Rarm_1.tres"),
	1 : preload("res://Character_Customization/Rarm/Rarm_2.tres"),
	2 : preload("res://Character_Customization/Rarm/Rarm_3.tres"),
	3 : preload("res://Character_Customization/Rarm/Rarm_4.tres"),
	4 : preload("res://Character_Customization/Rarm/Rarm_5.tres"),
	5 : preload("res://Character_Customization/Rarm/Rarm_6.tres"),
	6 : preload("res://Character_Customization/Rarm/Rarm_7.tres"),
	7 : preload("res://Character_Customization/Rarm/Rarm_8.tres"),
	8 : preload("res://Character_Customization/Rarm/Rarm_9.tres"),
	9 : preload("res://Character_Customization/Rarm/Rarm_10.tres"),
	10 : preload("res://Character_Customization/Rarm/Rarm_11.tres"),
	11 : preload("res://Character_Customization/Rarm/Rarm_12.tres"),
	12 : preload("res://Character_Customization/Rarm/Rarm_13.tres"),
	13 : preload("res://Character_Customization/Rarm/Rarm_14.tres"),
	14 : preload("res://Character_Customization/Rarm/Rarm_15.tres"),
	15 : preload("res://Character_Customization/Rarm/Rarm_16.tres"),
}
const Headgear_preload = {
	0 : preload("res://Character_Customization/Headgear/Headgear_1.tres"),
	1 : preload("res://Character_Customization/Headgear/Headgear_2.tres"),
	2 : preload("res://Character_Customization/Headgear/Headgear_3.tres"),
	3 : preload("res://Character_Customization/Headgear/Headgear_4.tres"),
	4 : preload("res://Character_Customization/Headgear/Headgear_5.tres"),
}
const Hair_Preload = {
	0 : preload("res://Character_Customization/Headgear/Headgear_10.tres"),
	1 : preload("res://Character_Customization/Headgear/Headgear_11.tres"),
	2 : preload("res://Character_Customization/Headgear/Headgear_12.tres"),
}

const Skintone = {
	0 : preload("res://Character_Customization/Testures/PinkLight.material"),
	1 : preload("res://Character_Customization/Testures/Brown.material"),
	2 : preload("res://Character_Customization/Testures/OrangeDark.material"),
	3 : preload("res://Character_Customization/Testures/BrownDarkSkin.material"),
	4 : preload("res://Character_Customization/Testures/Copper.material"),
}
